theme: jekyll-theme-cayman

### content configuration ###
title:       "Exemplar Generative Adversarial Networks (ExGANs)"
keywords:    "machine learning, gans, inpainting, eye opening"
description: "Using reference data to improve in-painting"
