theme: jekyll-theme-slate

### content configuration ###
title:       "Eye In-painting with Exemplar Generative Adversarial Networks (ExGANs)"
keywords:    "machine learning, gans, inpainting, eye opening"
description: "Using reference data to improve in-painting"
